### ISSUE TITLE
Data Visualization Projects - Visualize Data with a Bar Chart - Test 10 failure

### ISSUE THREAD

**Issue by k-sav** [freeCodeCamp/testable-projects-fcc#599]
#### Issue Description
Test 10 is failing and I'm not even sure how it is attempting to test for 'alignment'.

```
10. The data-date attribute and its corresponding bar element should align with the corresponding value on the x-axis. Cannot read property 'length' of null 
TypeError: Cannot read property 'length' of null
```

#### Browser Information
Google Chrome
Version 68.0.3440.106 (Official Build) (64-bit)
* MacOS High Sierra 
* Desktop 

#### Your Code / Link to Your Pen
[Codepen](https://codepen.io/k-sav/pen/PdeRRj)

**Comment by tbushman** [comment]
@kris-savoia Thanks for your patience. This should be fixed when #546 is merged. I'll check back with you.

**Comment by tbushman** [comment]
This project implements wider `<rect>` elements than the current error margin of 11px. That is valid, however I'm guessing you'll have better test success if the bars are thinner. @k-sav will you please try it with thinner bars and let me know if that helps?

**Comment by k-sav** [comment]
@tbushman 
I tried   
`const barWidth = 2;` instead of 
`const barWidth = x.bandwidth();`
Test 10 is still failing in the same way.

**Comment by tbushman** [comment]
@k-sav OK sorry. It's only three bars failing alignment on either end of the axis -- not sure why. The pen will pass if there are fewer axis ticks:  
```  
xaxis.call(d3.axisBottom(x).tickValues(x.domain().filter(function(d,i){ return !(i%4)})))  
```  
... but not always (i.e. `i%5` doesn't pass) :/  
Keeping this open to reference a fix so that `surroundingTicks` is an empty array instead of null in such cases.

**Comment by ValeraS** [comment]
resolved
